---
- name: Install cassandra on node 1 
  hosts: "{{ ipnode1 }}"
  remote_user:"{{ remote_user }}"
  sudo: True

  roles:
    - jdk_1.8
    - cassandra_node2
   
- name: Install cassandra on node 2
  hosts: "{{ ipnode2 }}"
  remote_user: "{{ remote_user }}"
  sudo: True

  roles:
    - jdk_1.8
    - cassandra_node1
